using DB.RTAComp.Tables;
using Microsoft.EntityFrameworkCore;

namespace DB.RTAComp
{
    public class compDbContext : DbContext
    {
        public compDbContext(DbContextOptions<compDbContext> options) : base(options)
        {

        }

        public virtual DbSet<A1_Tables_Datatype_Info_Master> A1_Tables_Datatype_Info_Master { get; set; }
        public virtual DbSet<A1_Tables_Info_Master_Main> A1_Tables_Info_Master_Main { get; set; }
        public virtual DbSet<A1_Tables_Info_Master_Main_Manual> A1_Tables_Info_Master_Main_Manual { get; set; }
        public virtual DbSet<All_Table_Rpt_Tmp> All_Table_Rpt_Tmp { get; set; }
        public virtual DbSet<Balance_Sheet> Balance_Sheet { get; set; }
        public virtual DbSet<Bepos_Dates_Tmp> Bepos_Dates_Tmp { get; set; }
        public virtual DbSet<Bepos_Dates_Tmp_4_Arrange> Bepos_Dates_Tmp_4_Arrange { get; set; }
        public virtual DbSet<Bepos_Dates_Tmp_To_Be_Delete> Bepos_Dates_Tmp_To_Be_Delete { get; set; }
        public virtual DbSet<Category_Master> Category_Master { get; set; }
        public virtual DbSet<Categroy_Converted_Master> Categroy_Converted_Master { get; set; }
        public virtual DbSet<Cdsl_Master> Cdsl_Master { get; set; }
        public virtual DbSet<Cdsl_Master_01> Cdsl_Master_01 { get; set; }
        public virtual DbSet<Cdsl_Master_02> Cdsl_Master_02 { get; set; }
        public virtual DbSet<City_Master> City_Master { get; set; }
        public virtual DbSet<City_State_Master> City_State_Master { get; set; }
        public virtual DbSet<Comp_Hold_Det_Mst> Comp_Hold_Det_Mst { get; set; }
        public virtual DbSet<Comp_Holding_Trx_Detail> Comp_Holding_Trx_Detail { get; set; }
        public virtual DbSet<Comp_Name> Comp_Name { get; set; }
        public virtual DbSet<Comp_Opening_Holding> Comp_Opening_Holding { get; set; }
        public virtual DbSet<Comp_Per_Day_Holding_Det> Comp_Per_Day_Holding_Det { get; set; }
        public virtual DbSet<Company_Benpos_History_Master> Company_Benpos_History_Master { get; set; }
        public virtual DbSet<Company_Ca_History_Detail> Company_Ca_History_Detail { get; set; }
        public virtual DbSet<Company_Ca_History_Detail_08072022_T_111401> Company_Ca_History_Detail_08072022_T_111401 { get; set; }
        public virtual DbSet<Country_Tmp_Detail_All> Country_Tmp_Detail_All { get; set; }
        public virtual DbSet<Demat_Batch_Id_Master> Demat_Batch_Id_Master { get; set; }
        public virtual DbSet<Distribution_Master> Distribution_Master { get; set; }
        public virtual DbSet<Distribution_Tmp_1> Distribution_Tmp_1 { get; set; }
        public virtual DbSet<Distribution_Tmp_2> Distribution_Tmp_2 { get; set; }
        public virtual DbSet<Dnr_Upload_0> Dnr_Upload_0 { get; set; }
        public virtual DbSet<Dnr_Upload_1> Dnr_Upload_1 { get; set; }
        public virtual DbSet<Dnr_Upload_2> Dnr_Upload_2 { get; set; }
        public virtual DbSet<Dnr_Upload_3> Dnr_Upload_3 { get; set; }
        public virtual DbSet<E_Upload_Cdsl_Detail> E_Upload_Cdsl_Detail { get; set; }
        public virtual DbSet<E_Upload_Cdsl_Detail_Dn> E_Upload_Cdsl_Detail_Dn { get; set; }
        public virtual DbSet<E_Upload_Cdsl_Header> E_Upload_Cdsl_Header { get; set; }
        public virtual DbSet<E_Upload_Nsdl> E_Upload_Nsdl { get; set; }
        public virtual DbSet<E_Upload_Rpt_Tmp> E_Upload_Rpt_Tmp { get; set; }
        public virtual DbSet<E_Vote_4_Print> E_Vote_4_Print { get; set; }
        public virtual DbSet<E_Vote_Cdsl_Master> E_Vote_Cdsl_Master { get; set; }
        public virtual DbSet<E_Vote_Id_Master_Cdsl> E_Vote_Id_Master_Cdsl { get; set; }
        public virtual DbSet<E_Vote_Id_Master_Nsdl> E_Vote_Id_Master_Nsdl { get; set; }
        public virtual DbSet<E_Vote_Nsdl_Master> E_Vote_Nsdl_Master { get; set; }
        public virtual DbSet<E_Vote_Tmp_Detail_All> E_Vote_Tmp_Detail_All { get; set; }
        public virtual DbSet<Exch_Master_01_Cdsl_1718> Exch_Master_01_Cdsl_1718 { get; set; }
        public virtual DbSet<Exch_Master_01_Cdsl_1819> Exch_Master_01_Cdsl_1819 { get; set; }
        public virtual DbSet<Exch_Master_01_Cdsl_1920> Exch_Master_01_Cdsl_1920 { get; set; }
        public virtual DbSet<Exch_Master_01_Cdsl_2021> Exch_Master_01_Cdsl_2021 { get; set; }
        public virtual DbSet<Exch_Master_01_Cdsl_2122> Exch_Master_01_Cdsl_2122 { get; set; }
        public virtual DbSet<Exch_Master_01_Cdsl_2223> Exch_Master_01_Cdsl_2223 { get; set; }
        public virtual DbSet<Exch_Master_01_Nsdl_1718> Exch_Master_01_Nsdl_1718 { get; set; }
        public virtual DbSet<Exch_Master_01_Nsdl_1819> Exch_Master_01_Nsdl_1819 { get; set; }
        public virtual DbSet<Exch_Master_01_Nsdl_1920> Exch_Master_01_Nsdl_1920 { get; set; }
        public virtual DbSet<Exch_Master_01_Nsdl_2021> Exch_Master_01_Nsdl_2021 { get; set; }
        public virtual DbSet<Exch_Master_01_Nsdl_2122> Exch_Master_01_Nsdl_2122 { get; set; }
        public virtual DbSet<Exch_Master_01_Nsdl_2223> Exch_Master_01_Nsdl_2223 { get; set; }
        public virtual DbSet<Exch_Master_02_Cdsl_1718> Exch_Master_02_Cdsl_1718 { get; set; }
        public virtual DbSet<Exch_Master_02_Cdsl_1819> Exch_Master_02_Cdsl_1819 { get; set; }
        public virtual DbSet<Exch_Master_02_Cdsl_1920> Exch_Master_02_Cdsl_1920 { get; set; }
        public virtual DbSet<Exch_Master_02_Cdsl_2021> Exch_Master_02_Cdsl_2021 { get; set; }
        public virtual DbSet<Exch_Master_02_Cdsl_2122> Exch_Master_02_Cdsl_2122 { get; set; }
        public virtual DbSet<Exch_Master_02_Cdsl_2223> Exch_Master_02_Cdsl_2223 { get; set; }
        public virtual DbSet<Exch_Master_02_Nsdl_1718> Exch_Master_02_Nsdl_1718 { get; set; }
        public virtual DbSet<Exch_Master_02_Nsdl_1819> Exch_Master_02_Nsdl_1819 { get; set; }
        public virtual DbSet<Exch_Master_02_Nsdl_1920> Exch_Master_02_Nsdl_1920 { get; set; }
        public virtual DbSet<Exch_Master_02_Nsdl_2021> Exch_Master_02_Nsdl_2021 { get; set; }
        public virtual DbSet<Exch_Master_02_Nsdl_2122> Exch_Master_02_Nsdl_2122 { get; set; }
        public virtual DbSet<Exch_Master_02_Nsdl_2223> Exch_Master_02_Nsdl_2223 { get; set; }
        public virtual DbSet<Exch_Master_03_Nsdl_1718> Exch_Master_03_Nsdl_1718 { get; set; }
        public virtual DbSet<Exch_Master_03_Nsdl_1819> Exch_Master_03_Nsdl_1819 { get; set; }
        public virtual DbSet<Exch_Master_03_Nsdl_1920> Exch_Master_03_Nsdl_1920 { get; set; }
        public virtual DbSet<Exch_Master_03_Nsdl_2021> Exch_Master_03_Nsdl_2021 { get; set; }
        public virtual DbSet<Exch_Master_03_Nsdl_2122> Exch_Master_03_Nsdl_2122 { get; set; }
        public virtual DbSet<Exch_Master_03_Nsdl_2223> Exch_Master_03_Nsdl_2223 { get; set; }
        public virtual DbSet<Holding_As_On_Date_Master> Holding_As_On_Date_Master { get; set; }
        public virtual DbSet<Hsn_Code_List> Hsn_Code_List { get; set; }
        public virtual DbSet<Hsn_Code_With_Rate> Hsn_Code_With_Rate { get; set; }
        public virtual DbSet<Iepf_Detail_Cdsl_Ndsl> Iepf_Detail_Cdsl_Ndsl { get; set; }
        public virtual DbSet<Iepf_Detail_Cdsl_Phy> Iepf_Detail_Cdsl_Phy { get; set; }
        public virtual DbSet<Iepf_Detail_Cdsl_Phy_Dnr> Iepf_Detail_Cdsl_Phy_Dnr { get; set; }
        public virtual DbSet<Iepf_Detail_Ndsl_Ndsl> Iepf_Detail_Ndsl_Ndsl { get; set; }
        public virtual DbSet<Iepf_Detail_Nsdl_Cdsl_Phy_Dnr> Iepf_Detail_Nsdl_Cdsl_Phy_Dnr { get; set; }
        public virtual DbSet<Iepf_Detail_Nsdl_Phy> Iepf_Detail_Nsdl_Phy { get; set; }
        public virtual DbSet<Iepf_Detail_Nsdl_Phy_Dnr> Iepf_Detail_Nsdl_Phy_Dnr { get; set; }
        public virtual DbSet<Iepf_Header_4_All_Exch_Nsdl> Iepf_Header_4_All_Exch_Nsdl { get; set; }
        public virtual DbSet<Iepf_Header_4_Exch_Cdsl> Iepf_Header_4_Exch_Cdsl { get; set; }
        public virtual DbSet<Index_Texla1_Tmp_Master> Index_Texla1_Tmp_Master { get; set; }
        public virtual DbSet<Index_Tmp_Detail> Index_Tmp_Detail { get; set; }
        public virtual DbSet<Index_Tmp_Detail_All> Index_Tmp_Detail_All { get; set; }
        public virtual DbSet<Index_Tmp_Detail_All_Ready_4_Export> Index_Tmp_Detail_All_Ready_4_Export { get; set; }
        public virtual DbSet<Index_Tmp_Detail_All_Save_4_Futre> Index_Tmp_Detail_All_Save_4_Futre { get; set; }
        public virtual DbSet<Index_Tmp_Detail_All_Updated_Report> Index_Tmp_Detail_All_Updated_Report { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Cdsl> Index_Tmp_Detail_Cdsl { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Consolidted> Index_Tmp_Detail_Consolidted { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Current> Index_Tmp_Detail_Current { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Phy> Index_Tmp_Detail_Phy { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Phy_Error> Index_Tmp_Detail_Phy_Error { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Weeking> Index_Tmp_Detail_Weeking { get; set; }
        public virtual DbSet<Index_Tmp_Detail_Weeking_2> Index_Tmp_Detail_Weeking_2 { get; set; }
        public virtual DbSet<Index_Tmp_Promoter_List> Index_Tmp_Promoter_List { get; set; }
        public virtual DbSet<Index_Tmp_Promoter_List2> Index_Tmp_Promoter_List2 { get; set; }
        public virtual DbSet<Item_Master> Item_Master { get; set; }
        public virtual DbSet<Item_Trn> Item_Trn { get; set; }
        public virtual DbSet<Last_Quarter_Master> Last_Quarter_Master { get; set; }
        public virtual DbSet<Maker_Checker_Log_Master> Maker_Checker_Log_Master { get; set; }
        public virtual DbSet<Month_Table> Month_Table { get; set; }
        public virtual DbSet<Narration_Master> Narration_Master { get; set; }
        public virtual DbSet<Nri_Tmp_Detail_All> Nri_Tmp_Detail_All { get; set; }
        public virtual DbSet<Nsdl_Cdls_Tmp_Rpt_Master> Nsdl_Cdls_Tmp_Rpt_Master { get; set; }
        public virtual DbSet<Nsdl_Cdls_Tmp_Rpt_Master2> Nsdl_Cdls_Tmp_Rpt_Master2 { get; set; }
        public virtual DbSet<Nsdl_Master> Nsdl_Master { get; set; }
        public virtual DbSet<Nsdl_Master_01> Nsdl_Master_01 { get; set; }
        public virtual DbSet<Nsdl_Master_02> Nsdl_Master_02 { get; set; }
        public virtual DbSet<Old_Texla1> Old_Texla1 { get; set; }
        public virtual DbSet<Old_Texla1_13022022_141656> Old_Texla1_13022022_141656 { get; set; }
        public virtual DbSet<Old_Texla2> Old_Texla2 { get; set; }
        public virtual DbSet<Panno_Update_With_Demat> Panno_Update_With_Demat { get; set; }
        public virtual DbSet<Partymaster> Partymaster { get; set; }
        public virtual DbSet<Partymaster_System> Partymaster_System { get; set; }
        public virtual DbSet<Partytrn> Partytrn { get; set; }
        public virtual DbSet<Per_Day_Holding_All_Comp> Per_Day_Holding_All_Comp { get; set; }
        public virtual DbSet<Prawuse> Prawuse { get; set; }
        public virtual DbSet<Promoter_Master> Promoter_Master { get; set; }
        public virtual DbSet<Promoter_Master_Tmp> Promoter_Master_Tmp { get; set; }
        public virtual DbSet<Qtr_Regulation_Pattern_Master> Qtr_Regulation_Pattern_Master { get; set; }
        public virtual DbSet<Qtr_Regulation_Pattern_Master_Promo> Qtr_Regulation_Pattern_Master_Promo { get; set; }
        public virtual DbSet<Qtr_Regulation_Remark_Master> Qtr_Regulation_Remark_Master { get; set; }
        public virtual DbSet<Qtr_Statement_Declare_Master> Qtr_Statement_Declare_Master { get; set; }
        public virtual DbSet<Rejres> Rejres { get; set; }
        public virtual DbSet<Req_Rec_Certi_Details> Req_Rec_Certi_Details { get; set; }
        public virtual DbSet<Sebi_Rpt_Detail_Phy> Sebi_Rpt_Detail_Phy { get; set; }
        public virtual DbSet<Sebi_Rpt_Detail_Phy_Tmp> Sebi_Rpt_Detail_Phy_Tmp { get; set; }
        public virtual DbSet<Share_Qty_Slab_Master> Share_Qty_Slab_Master { get; set; }
        public virtual DbSet<State_Master> State_Master { get; set; }
        public virtual DbSet<Station> Station { get; set; }
        public virtual DbSet<Stock_Tmp_Table> Stock_Tmp_Table { get; set; }
        public virtual DbSet<System_Records> System_Records { get; set; }
        public virtual DbSet<Texla1> Texla1 { get; set; }
        public virtual DbSet<Texla1_13022022_141501> Texla1_13022022_141501 { get; set; }
        public virtual DbSet<Texla1_13022022_141659> Texla1_13022022_141659 { get; set; }
        public virtual DbSet<Texla1_Duplicate> Texla1_Duplicate { get; set; }
        public virtual DbSet<Texla1_Log> Texla1_Log { get; set; }
        public virtual DbSet<Texla1_Tmp_E_Vote_Cdsl> Texla1_Tmp_E_Vote_Cdsl { get; set; }
        public virtual DbSet<Texla1_Tmp_Master> Texla1_Tmp_Master { get; set; }
        public virtual DbSet<Texla2> Texla2 { get; set; }
        public virtual DbSet<Texla2_13022022_141615> Texla2_13022022_141615 { get; set; }
        public virtual DbSet<Texla2_Bepos> Texla2_Bepos { get; set; }
        public virtual DbSet<Texla2_Bepos_Backup> Texla2_Bepos_Backup { get; set; }
        public virtual DbSet<Texla2_Detail_Rpt> Texla2_Detail_Rpt { get; set; }
        public virtual DbSet<Texla2_Last_Certi_No_Tmp> Texla2_Last_Certi_No_Tmp { get; set; }
        public virtual DbSet<Texla2_Opening> Texla2_Opening { get; set; }
        public virtual DbSet<Texla2_Opening_Benpos> Texla2_Opening_Benpos { get; set; }
        public virtual DbSet<Texla2_Opening_Tmp> Texla2_Opening_Tmp { get; set; }
        public virtual DbSet<Texla2_Req_Rec_Tmp> Texla2_Req_Rec_Tmp { get; set; }
        public virtual DbSet<Texla2_Tmp> Texla2_Tmp { get; set; }
        public virtual DbSet<Texla2_Tmp_4_Cert> Texla2_Tmp_4_Cert { get; set; }
        public virtual DbSet<Tmp_Ca_Upload_01> Tmp_Ca_Upload_01 { get; set; }
        public virtual DbSet<Tmp_Ca_Upload_02> Tmp_Ca_Upload_02 { get; set; }
        public virtual DbSet<Tmp_Ca_Upload_03> Tmp_Ca_Upload_03 { get; set; }
        public virtual DbSet<Tmp_Ca_Upload_04> Tmp_Ca_Upload_04 { get; set; }
        public virtual DbSet<Tmp_Promoter_Master> Tmp_Promoter_Master { get; set; }
        public virtual DbSet<Tr_All_Master> Tr_All_Master { get; set; }
        public virtual DbSet<Tr_All_Master_4_Error_Records> Tr_All_Master_4_Error_Records { get; set; }
        public virtual DbSet<Tr_All_Master_4_Opening> Tr_All_Master_4_Opening { get; set; }
        public virtual DbSet<Tr_All_Master_Log> Tr_All_Master_Log { get; set; }
        public virtual DbSet<Tr_All_Master_Tmp1> Tr_All_Master_Tmp1 { get; set; }
        public virtual DbSet<Tr_All_Master_Tmp100> Tr_All_Master_Tmp100 { get; set; }
        public virtual DbSet<Tr_All_Master_Tmp100_Log> Tr_All_Master_Tmp100_Log { get; set; }
        public virtual DbSet<Tr_All_Master_Tmp2> Tr_All_Master_Tmp2 { get; set; }
        public virtual DbSet<Tr_All_Master_Tmp200> Tr_All_Master_Tmp200 { get; set; }
        public virtual DbSet<Tr_All_Master_Tmp200_Log> Tr_All_Master_Tmp200_Log { get; set; }
        public virtual DbSet<Tr_Change_Add> Tr_Change_Add { get; set; }
        public virtual DbSet<Tr_Change_Add_Log> Tr_Change_Add_Log { get; set; }
        public virtual DbSet<Tr_Consol> Tr_Consol { get; set; }
        public virtual DbSet<Tr_Consol_Deleted> Tr_Consol_Deleted { get; set; }
        public virtual DbSet<Tr_Consol_Deleted_Log> Tr_Consol_Deleted_Log { get; set; }
        public virtual DbSet<Tr_Consol_Log> Tr_Consol_Log { get; set; }
        public virtual DbSet<Tr_Duplicate> Tr_Duplicate { get; set; }
        public virtual DbSet<Tr_Duplicate_Deleted> Tr_Duplicate_Deleted { get; set; }
        public virtual DbSet<Tr_Duplicate_Deleted_Log> Tr_Duplicate_Deleted_Log { get; set; }
        public virtual DbSet<Tr_Duplicate_Log> Tr_Duplicate_Log { get; set; }
        public virtual DbSet<Tr_Iepf_Data_By_Company> Tr_Iepf_Data_By_Company { get; set; }
        public virtual DbSet<Tr_Iepf_Master> Tr_Iepf_Master { get; set; }
        public virtual DbSet<Tr_Kyc_Address_Multi_Trx> Tr_Kyc_Address_Multi_Trx { get; set; }
        public virtual DbSet<Tr_Kyc_Address_Multi_Trx_Log> Tr_Kyc_Address_Multi_Trx_Log { get; set; }
        public virtual DbSet<Tr_Kyc_Finance_Multi_Trx> Tr_Kyc_Finance_Multi_Trx { get; set; }
        public virtual DbSet<Tr_Kyc_Finance_Multi_Trx_Log> Tr_Kyc_Finance_Multi_Trx_Log { get; set; }
        public virtual DbSet<Tr_Kyc_Nominee_Multi_Trx> Tr_Kyc_Nominee_Multi_Trx { get; set; }
        public virtual DbSet<Tr_Kyc_Nominee_Multi_Trx_Log> Tr_Kyc_Nominee_Multi_Trx_Log { get; set; }
        public virtual DbSet<Tr_Kyc_Update_Multi_Trx_Master_Detail> Tr_Kyc_Update_Multi_Trx_Master_Detail { get; set; }
        public virtual DbSet<Tr_Kyc_Update_Multi_Trx_Master_Detail_Log> Tr_Kyc_Update_Multi_Trx_Master_Detail_Log { get; set; }
        public virtual DbSet<Tr_Lost> Tr_Lost { get; set; }
        public virtual DbSet<Tr_Lost_Deleted> Tr_Lost_Deleted { get; set; }
        public virtual DbSet<Tr_Lost_Deleted_Log> Tr_Lost_Deleted_Log { get; set; }
        public virtual DbSet<Tr_Lost_Log> Tr_Lost_Log { get; set; }
        public virtual DbSet<Tr_Menu_Master> Tr_Menu_Master { get; set; }
        public virtual DbSet<Tr_Name_Correction> Tr_Name_Correction { get; set; }
        public virtual DbSet<Tr_Name_Correction_Log> Tr_Name_Correction_Log { get; set; }
        public virtual DbSet<Tr_Name_Mis_Match_Detail> Tr_Name_Mis_Match_Detail { get; set; }
        public virtual DbSet<Tr_Name_Mis_Match_Detail_Log> Tr_Name_Mis_Match_Detail_Log { get; set; }
        public virtual DbSet<Tr_Name_Mis_Match_Detail_Trx> Tr_Name_Mis_Match_Detail_Trx { get; set; }
        public virtual DbSet<Tr_Name_Mis_Match_Detail_Trx_Log> Tr_Name_Mis_Match_Detail_Trx_Log { get; set; }
        public virtual DbSet<Tr_Name_Mis_Match_Detail_Trx_Tmp> Tr_Name_Mis_Match_Detail_Trx_Tmp { get; set; }
        public virtual DbSet<Tr_Nominee> Tr_Nominee { get; set; }
        public virtual DbSet<Tr_Nominee_Log> Tr_Nominee_Log { get; set; }
        public virtual DbSet<Tr_Phy_To_Cdsl> Tr_Phy_To_Cdsl { get; set; }
        public virtual DbSet<Tr_Phy_To_Cdsl_Log> Tr_Phy_To_Cdsl_Log { get; set; }
        public virtual DbSet<Tr_Phy_To_Nsdl> Tr_Phy_To_Nsdl { get; set; }
        public virtual DbSet<Tr_Phy_To_Nsdl_Log> Tr_Phy_To_Nsdl_Log { get; set; }
        public virtual DbSet<Tr_Phy_To_Phy> Tr_Phy_To_Phy { get; set; }
        public virtual DbSet<Tr_Phy_To_Phy_Log> Tr_Phy_To_Phy_Log { get; set; }
        public virtual DbSet<Tr_Phy_To_Phy_Rpt_Tmp> Tr_Phy_To_Phy_Rpt_Tmp { get; set; }
        public virtual DbSet<Tr_Remat_Cdsl> Tr_Remat_Cdsl { get; set; }
        public virtual DbSet<Tr_Remat_Cdsl_Deleted> Tr_Remat_Cdsl_Deleted { get; set; }
        public virtual DbSet<Tr_Remat_Cdsl_Deleted_Log> Tr_Remat_Cdsl_Deleted_Log { get; set; }
        public virtual DbSet<Tr_Remat_Cdsl_Log> Tr_Remat_Cdsl_Log { get; set; }
        public virtual DbSet<Tr_Remat_Nsdl> Tr_Remat_Nsdl { get; set; }
        public virtual DbSet<Tr_Remat_Nsdl_Deleted> Tr_Remat_Nsdl_Deleted { get; set; }
        public virtual DbSet<Tr_Remat_Nsdl_Deleted_Log> Tr_Remat_Nsdl_Deleted_Log { get; set; }
        public virtual DbSet<Tr_Remat_Nsdl_Log> Tr_Remat_Nsdl_Log { get; set; }
        public virtual DbSet<Tr_Split> Tr_Split { get; set; }
        public virtual DbSet<Tr_Split_Deleted> Tr_Split_Deleted { get; set; }
        public virtual DbSet<Tr_Split_Deleted_Log> Tr_Split_Deleted_Log { get; set; }
        public virtual DbSet<Tr_Split_Log> Tr_Split_Log { get; set; }
        public virtual DbSet<Tr_Stop_Or_Lock> Tr_Stop_Or_Lock { get; set; }
        public virtual DbSet<Tr_Stop_Or_Lock_Log> Tr_Stop_Or_Lock_Log { get; set; }
        public virtual DbSet<Tr_To_Ca_Master_Detail_02> Tr_To_Ca_Master_Detail_02 { get; set; }
        public virtual DbSet<Tr_To_Ca_Master_Detail_02_Phy> Tr_To_Ca_Master_Detail_02_Phy { get; set; }
        public virtual DbSet<Tr_To_Ca_Master_Dnr_03> Tr_To_Ca_Master_Dnr_03 { get; set; }
        public virtual DbSet<Tr_To_Ca_Master_Dnr_03_Phy> Tr_To_Ca_Master_Dnr_03_Phy { get; set; }
        public virtual DbSet<Tr_To_Ca_Master_Main_01> Tr_To_Ca_Master_Main_01 { get; set; }
        public virtual DbSet<Tr_To_Iepf> Tr_To_Iepf { get; set; }
        public virtual DbSet<Tr_To_Iepf_Log> Tr_To_Iepf_Log { get; set; }
        public virtual DbSet<Tr_To_Power_Attorney> Tr_To_Power_Attorney { get; set; }
        public virtual DbSet<Tr_To_Power_Attorney_Log> Tr_To_Power_Attorney_Log { get; set; }
        public virtual DbSet<Tr_Transm> Tr_Transm { get; set; }
        public virtual DbSet<Tr_Transm_Log> Tr_Transm_Log { get; set; }
        public virtual DbSet<Tr_Update_Pan_Card> Tr_Update_Pan_Card { get; set; }
        public virtual DbSet<Tr_Update_Pan_Card_Log> Tr_Update_Pan_Card_Log { get; set; }
        public virtual DbSet<Tran_Detail_Tmp> Tran_Detail_Tmp { get; set; }
        public virtual DbSet<Transporter_Name> Transporter_Name { get; set; }
        public virtual DbSet<Upload_Id_Master_Nsdl_Cdsl> Upload_Id_Master_Nsdl_Cdsl { get; set; }
        public virtual DbSet<Upload_Master_4_Print> Upload_Master_4_Print { get; set; }
        public virtual DbSet<Upload_Master_Nsdl_Cdsl> Upload_Master_Nsdl_Cdsl { get; set; }
       

        
        protected override void OnModelCreating(ModelBuilder builder)
        {      
            
        }

    }

}

 
