// <auto-generated />
using System;
using DB.Login;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Login.Migrations
{
    [DbContext(typeof(loginDBContext))]
    [Migration("20240119123754_login_db_v_106")]
    partial class login_db_v_106
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DB.Login.Tables.ApplicationMaster", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint auto_increment")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("coWorker_name")
                        .HasColumnType("text")
                        .HasColumnName("coWorker_name")
                        .HasColumnOrder(17);

                    b.Property<DateTime?>("coming_date")
                        .HasColumnType("date")
                        .HasColumnName("coming_date")
                        .HasColumnOrder(20);

                    b.Property<DateTime?>("date")
                        .HasColumnType("date")
                        .HasColumnName("date")
                        .HasColumnOrder(8);

                    b.Property<string>("designation")
                        .HasColumnType("text")
                        .HasColumnName("designation")
                        .HasColumnOrder(23);

                    b.Property<string>("disease")
                        .HasColumnType("text")
                        .HasColumnName("disease")
                        .HasColumnOrder(21);

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("date")
                        .HasColumnName("end_date")
                        .HasColumnOrder(19);

                    b.Property<string>("file_path")
                        .HasColumnType("text")
                        .HasColumnName("file_path")
                        .HasColumnOrder(22);

                    b.Property<string>("first_addres")
                        .HasColumnType("text")
                        .HasColumnName("first_addres")
                        .HasColumnOrder(3);

                    b.Property<string>("first_city")
                        .HasColumnType("text")
                        .HasColumnName("first_city")
                        .HasColumnOrder(4);

                    b.Property<string>("first_email")
                        .HasColumnType("text")
                        .HasColumnName("first_email")
                        .HasColumnOrder(2);

                    b.Property<string>("first_mobile")
                        .HasColumnType("text")
                        .HasColumnName("first_mobile")
                        .HasColumnOrder(7);

                    b.Property<string>("first_pincode")
                        .HasColumnType("text")
                        .HasColumnName("first_pincode")
                        .HasColumnOrder(6);

                    b.Property<string>("first_state")
                        .HasColumnType("text")
                        .HasColumnName("first_state")
                        .HasColumnOrder(5);

                    b.Property<string>("logo_image")
                        .HasColumnType("text")
                        .HasColumnName("logo_image")
                        .HasColumnOrder(24);

                    b.Property<string>("second_address")
                        .HasColumnType("text")
                        .HasColumnName("second_address")
                        .HasColumnOrder(10);

                    b.Property<string>("second_city")
                        .HasColumnType("text")
                        .HasColumnName("second_city")
                        .HasColumnOrder(11);

                    b.Property<string>("second_name")
                        .HasColumnType("text")
                        .HasColumnName("second_name")
                        .HasColumnOrder(9);

                    b.Property<string>("second_pincode")
                        .HasColumnType("text")
                        .HasColumnName("second_pincode")
                        .HasColumnOrder(13);

                    b.Property<string>("second_state")
                        .HasColumnType("text")
                        .HasColumnName("second_state")
                        .HasColumnOrder(12);

                    b.Property<string>("sign_image")
                        .HasColumnType("text")
                        .HasColumnName("sign_image")
                        .HasColumnOrder(25);

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("date")
                        .HasColumnName("start_date")
                        .HasColumnOrder(18);

                    b.Property<string>("subject")
                        .HasColumnType("text")
                        .HasColumnName("subject")
                        .HasColumnOrder(14);

                    b.Property<string>("total_day")
                        .HasColumnType("text")
                        .HasColumnName("total_day")
                        .HasColumnOrder(15);

                    b.Property<string>("type_of_leave")
                        .HasColumnType("text")
                        .HasColumnName("type_of_leave")
                        .HasColumnOrder(16);

                    b.HasKey("id");

                    b.ToTable("ApplicationMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.CategoryMaster", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<decimal?>("approx_amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("approx_amount")
                        .HasColumnOrder(3);

                    b.Property<int?>("approx_days")
                        .HasColumnType("int")
                        .HasColumnName("approx_days")
                        .HasColumnOrder(4);

                    b.Property<long?>("service_id")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id")
                        .HasColumnOrder(5);

                    b.Property<string>("service_type")
                        .HasColumnType("text")
                        .HasColumnName("service_type")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.HasIndex("service_id");

                    b.ToTable("CategoryMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.CheckListMaster", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long?>("category_id")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id")
                        .HasColumnOrder(4);

                    b.Property<string>("document_required_name")
                        .HasColumnType("text")
                        .HasColumnName("document_required_name")
                        .HasColumnOrder(2);

                    b.Property<string>("document_required_type")
                        .HasColumnType("text")
                        .HasColumnName("document_required_type")
                        .HasColumnOrder(3);

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("CheckListMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.CorrespondenceRequest", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint auto_increment")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("company_name")
                        .HasColumnType("text")
                        .HasColumnName("company_name")
                        .HasColumnOrder(2);

                    b.Property<DateTime?>("current_date")
                        .HasColumnType("date")
                        .HasColumnName("current_date")
                        .HasColumnOrder(11);

                    b.Property<string>("purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose")
                        .HasColumnOrder(6);

                    b.Property<string>("reject_yn")
                        .HasColumnType("text")
                        .HasColumnName("reject_yn")
                        .HasColumnOrder(4);

                    b.Property<DateTime?>("reply_date")
                        .HasColumnType("date")
                        .HasColumnName("reply_date")
                        .HasColumnOrder(3);

                    b.Property<string>("sender_email")
                        .HasColumnType("text")
                        .HasColumnName("sender_email")
                        .HasColumnOrder(8);

                    b.Property<long?>("sender_mobile")
                        .HasColumnType("bigint")
                        .HasColumnName("sender_mobile")
                        .HasColumnOrder(9);

                    b.Property<string>("sender_name")
                        .HasColumnType("text")
                        .HasColumnName("sender_name")
                        .HasColumnOrder(7);

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasColumnOrder(10);

                    b.Property<string>("work_category")
                        .HasColumnType("text")
                        .HasColumnName("work_category")
                        .HasColumnOrder(5);

                    b.HasKey("id");

                    b.ToTable("CorrespondenceRequest");
                });

            modelBuilder.Entity("DB.Login.Tables.GeneralRequestedDetail", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long?>("category_id")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id")
                        .HasColumnOrder(3);

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at")
                        .HasColumnOrder(7);

                    b.Property<long?>("service_id")
                        .HasColumnType("bigint")
                        .HasColumnName("service_id")
                        .HasColumnOrder(3);

                    b.Property<string>("status")
                        .HasColumnType("text")
                        .HasColumnName("status")
                        .HasColumnOrder(6);

                    b.Property<long?>("user_id")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.HasIndex("service_id");

                    b.ToTable("GeneralRequestedDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.HolderDetail", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint auto_increment")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("holder_address1")
                        .HasColumnType("text")
                        .HasColumnName("holder_address1")
                        .HasColumnOrder(7);

                    b.Property<string>("holder_address2")
                        .HasColumnType("text")
                        .HasColumnName("holder_address2")
                        .HasColumnOrder(8);

                    b.Property<string>("holder_city")
                        .HasColumnType("text")
                        .HasColumnName("holder_city")
                        .HasColumnOrder(9);

                    b.Property<string>("holder_country")
                        .HasColumnType("text")
                        .HasColumnName("holder_country")
                        .HasColumnOrder(11);

                    b.Property<string>("holder_dob")
                        .HasColumnType("text")
                        .HasColumnName("holder_dob")
                        .HasColumnOrder(4);

                    b.Property<string>("holder_email")
                        .HasColumnType("text")
                        .HasColumnName("holder_email")
                        .HasColumnOrder(12);

                    b.Property<string>("holder_fathername")
                        .HasColumnType("text")
                        .HasColumnName("holder_fathername")
                        .HasColumnOrder(6);

                    b.Property<string>("holder_folio_no")
                        .HasColumnType("text")
                        .HasColumnName("holder_folio_no")
                        .HasColumnOrder(17);

                    b.Property<string>("holder_fullname")
                        .HasColumnType("text")
                        .HasColumnName("holder_fullname")
                        .HasColumnOrder(2);

                    b.Property<string>("holder_gender")
                        .HasColumnType("text")
                        .HasColumnName("holder_gender")
                        .HasColumnOrder(3);

                    b.Property<string>("holder_kyc_updated")
                        .HasColumnType("text")
                        .HasColumnName("holder_kyc_updated")
                        .HasColumnOrder(16);

                    b.Property<string>("holder_occupation")
                        .HasColumnType("text")
                        .HasColumnName("holder_occupation")
                        .HasColumnOrder(5);

                    b.Property<string>("holder_phone")
                        .HasColumnType("text")
                        .HasColumnName("holder_phone")
                        .HasColumnOrder(13);

                    b.Property<string>("holder_pincard")
                        .HasColumnType("text")
                        .HasColumnName("holder_pincard")
                        .HasColumnOrder(15);

                    b.Property<string>("holder_pincode")
                        .HasColumnType("text")
                        .HasColumnName("holder_pincode")
                        .HasColumnOrder(14);

                    b.Property<string>("holder_state")
                        .HasColumnType("text")
                        .HasColumnName("holder_state")
                        .HasColumnOrder(10);

                    b.HasKey("id");

                    b.ToTable("HolderDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.KYCDetail", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint auto_increment")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("checker_id")
                        .HasColumnType("text")
                        .HasColumnName("checker_id")
                        .HasColumnOrder(50);

                    b.Property<string>("checker_name")
                        .HasColumnType("text")
                        .HasColumnName("checker_name")
                        .HasColumnOrder(51);

                    b.Property<string>("checker_remark")
                        .HasColumnType("text")
                        .HasColumnName("checker_remark")
                        .HasColumnOrder(52);

                    b.Property<string>("checker_status")
                        .HasColumnType("text")
                        .HasColumnName("checker_status")
                        .HasColumnOrder(53);

                    b.Property<DateTime?>("checker_status_created_on")
                        .HasColumnType("date")
                        .HasColumnName("checker_status_created_on")
                        .HasColumnOrder(54);

                    b.Property<string>("current_status")
                        .HasColumnType("text")
                        .HasColumnName("current_status")
                        .HasColumnOrder(55);

                    b.Property<long?>("holder_detail_id")
                        .HasColumnType("bigint")
                        .HasColumnName("holder_detail_id")
                        .HasColumnOrder(56);

                    b.Property<long?>("maker_id")
                        .HasColumnType("bigint")
                        .HasColumnName("maker_id")
                        .HasColumnOrder(45);

                    b.Property<string>("maker_name")
                        .HasColumnType("text")
                        .HasColumnName("maker_name")
                        .HasColumnOrder(46);

                    b.Property<string>("maker_remark")
                        .HasColumnType("text")
                        .HasColumnName("maker_remark")
                        .HasColumnOrder(47);

                    b.Property<string>("maker_status")
                        .HasColumnType("text")
                        .HasColumnName("maker_status")
                        .HasColumnOrder(48);

                    b.Property<DateTime?>("maker_status_created_on")
                        .HasColumnType("date")
                        .HasColumnName("maker_status_created_on")
                        .HasColumnOrder(49);

                    b.Property<decimal?>("master_inward_id")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("master_inward_id")
                        .HasColumnOrder(5);

                    b.Property<decimal?>("master_req_id")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("master_req_id")
                        .HasColumnOrder(4);

                    b.Property<decimal?>("master_trf_no")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("master_trf_no")
                        .HasColumnOrder(6);

                    b.Property<decimal?>("multi_master_trx_no")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("multi_master_trx_no")
                        .HasColumnOrder(3);

                    b.Property<string>("p_account_type")
                        .HasColumnType("text")
                        .HasColumnName("p_account_type")
                        .HasColumnOrder(12);

                    b.Property<string>("p_account_type_code")
                        .HasColumnType("text")
                        .HasColumnName("p_account_type_code")
                        .HasColumnOrder(10);

                    b.Property<string>("p_address_type_code_bank")
                        .HasColumnType("text")
                        .HasColumnName("p_address_type_code_bank")
                        .HasColumnOrder(8);

                    b.Property<string>("p_address_type_code_detail_bank")
                        .HasColumnType("text")
                        .HasColumnName("p_address_type_code_detail_bank")
                        .HasColumnOrder(9);

                    b.Property<string>("p_adhaar_no")
                        .HasColumnType("text")
                        .HasColumnName("p_adhaar_no")
                        .HasColumnOrder(29);

                    b.Property<string>("p_bank_ac_no")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_ac_no")
                        .HasColumnOrder(11);

                    b.Property<string>("p_bank_add1")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_add1")
                        .HasColumnOrder(16);

                    b.Property<string>("p_bank_add2")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_add2")
                        .HasColumnOrder(17);

                    b.Property<string>("p_bank_add3")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_add3")
                        .HasColumnOrder(18);

                    b.Property<string>("p_bank_city")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_city")
                        .HasColumnOrder(19);

                    b.Property<string>("p_bank_country")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_country")
                        .HasColumnOrder(22);

                    b.Property<string>("p_bank_ifsc_code")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_ifsc_code")
                        .HasColumnOrder(15);

                    b.Property<string>("p_bank_micrno")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_micrno")
                        .HasColumnOrder(14);

                    b.Property<string>("p_bank_name")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_name")
                        .HasColumnOrder(13);

                    b.Property<string>("p_bank_pincode")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_pincode")
                        .HasColumnOrder(21);

                    b.Property<string>("p_bank_state")
                        .HasColumnType("text")
                        .HasColumnName("p_bank_state")
                        .HasColumnOrder(20);

                    b.Property<string>("p_dl_no")
                        .HasColumnType("text")
                        .HasColumnName("p_dl_no")
                        .HasColumnOrder(31);

                    b.Property<string>("p_emailid")
                        .HasColumnType("text")
                        .HasColumnName("p_emailid")
                        .HasColumnOrder(33);

                    b.Property<string>("p_panno1")
                        .HasColumnType("text")
                        .HasColumnName("p_panno1")
                        .HasColumnOrder(26);

                    b.Property<string>("p_panno2")
                        .HasColumnType("text")
                        .HasColumnName("p_panno2")
                        .HasColumnOrder(27);

                    b.Property<string>("p_panno3")
                        .HasColumnType("text")
                        .HasColumnName("p_panno3")
                        .HasColumnOrder(28);

                    b.Property<string>("p_passport_no")
                        .HasColumnType("text")
                        .HasColumnName("p_passport_no")
                        .HasColumnOrder(32);

                    b.Property<string>("p_phone")
                        .HasColumnType("text")
                        .HasColumnName("p_phone")
                        .HasColumnOrder(34);

                    b.Property<string>("p_update_type_finance")
                        .HasColumnType("text")
                        .HasColumnName("p_update_type_finance")
                        .HasColumnOrder(7);

                    b.Property<string>("p_voter_id")
                        .HasColumnType("text")
                        .HasColumnName("p_voter_id")
                        .HasColumnOrder(30);

                    b.Property<string>("pan1_addhar_linked_yn")
                        .HasColumnType("text")
                        .HasColumnName("pan1_addhar_linked_yn")
                        .HasColumnOrder(35);

                    b.Property<string>("pan2_addhar_linked_yn")
                        .HasColumnType("text")
                        .HasColumnName("pan2_addhar_linked_yn")
                        .HasColumnOrder(36);

                    b.Property<string>("pan3_addhar_linked_yn")
                        .HasColumnType("text")
                        .HasColumnName("pan3_addhar_linked_yn")
                        .HasColumnOrder(37);

                    b.Property<string>("rejecte_yn")
                        .HasColumnType("text")
                        .HasColumnName("rejecte_yn")
                        .HasColumnOrder(39);

                    b.Property<string>("rr_flag_name")
                        .HasColumnType("text")
                        .HasColumnName("rr_flag_name")
                        .HasColumnOrder(38);

                    b.Property<string>("t_panno1")
                        .HasColumnType("text")
                        .HasColumnName("t_panno1")
                        .HasColumnOrder(23);

                    b.Property<string>("t_panno2")
                        .HasColumnType("text")
                        .HasColumnName("t_panno2")
                        .HasColumnOrder(24);

                    b.Property<string>("t_panno3")
                        .HasColumnType("text")
                        .HasColumnName("t_panno3")
                        .HasColumnOrder(25);

                    b.Property<decimal?>("table_trf_no")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("table_trf_no")
                        .HasColumnOrder(2);

                    b.Property<string>("verify_by_username")
                        .HasColumnType("text")
                        .HasColumnName("verify_by_username")
                        .HasColumnOrder(41);

                    b.Property<string>("verify_remark")
                        .HasColumnType("text")
                        .HasColumnName("verify_remark")
                        .HasColumnOrder(43);

                    b.Property<string>("verify_status_msg")
                        .HasColumnType("text")
                        .HasColumnName("verify_status_msg")
                        .HasColumnOrder(42);

                    b.Property<DateTime?>("verify_updated_on")
                        .HasColumnType("date")
                        .HasColumnName("verify_updated_on")
                        .HasColumnOrder(44);

                    b.Property<string>("verify_yn")
                        .HasColumnType("text")
                        .HasColumnName("verify_yn")
                        .HasColumnOrder(40);

                    b.HasKey("id");

                    b.HasIndex("holder_detail_id");

                    b.ToTable("KYCDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.NomineeDetail", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("checker_id")
                        .HasColumnType("text")
                        .HasColumnName("checker_id")
                        .HasColumnOrder(46);

                    b.Property<string>("checker_name")
                        .HasColumnType("text")
                        .HasColumnName("checker_name")
                        .HasColumnOrder(47);

                    b.Property<string>("checker_remark")
                        .HasColumnType("text")
                        .HasColumnName("checker_remark")
                        .HasColumnOrder(48);

                    b.Property<string>("checker_status")
                        .HasColumnType("text")
                        .HasColumnName("checker_status")
                        .HasColumnOrder(49);

                    b.Property<DateTime?>("checker_status_created_on")
                        .HasColumnType("datetime")
                        .HasColumnName("checker_status_created_on")
                        .HasColumnOrder(50);

                    b.Property<string>("current_status")
                        .HasColumnType("text")
                        .HasColumnName("current_status")
                        .HasColumnOrder(51);

                    b.Property<long?>("holder_detail_id")
                        .HasColumnType("bigint")
                        .HasColumnName("holder_detail_id")
                        .HasColumnOrder(53);

                    b.Property<string>("maker_id")
                        .HasColumnType("text")
                        .HasColumnName("maker_id")
                        .HasColumnOrder(41);

                    b.Property<string>("maker_name")
                        .HasColumnType("text")
                        .HasColumnName("maker_name")
                        .HasColumnOrder(42);

                    b.Property<string>("maker_remark")
                        .HasColumnType("text")
                        .HasColumnName("maker_remark")
                        .HasColumnOrder(43);

                    b.Property<string>("maker_status")
                        .HasColumnType("text")
                        .HasColumnName("maker_status")
                        .HasColumnOrder(44);

                    b.Property<DateTime?>("maker_status_created_on")
                        .HasColumnType("datetime")
                        .HasColumnName("maker_status_created_on")
                        .HasColumnOrder(45);

                    b.Property<decimal?>("master_inward_id")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("master_inward_id")
                        .HasColumnOrder(4);

                    b.Property<decimal?>("master_req_id")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("master_req_id")
                        .HasColumnOrder(3);

                    b.Property<decimal?>("master_trf_no")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("master_trf_no")
                        .HasColumnOrder(5);

                    b.Property<decimal?>("multi_master_trx_no")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("multi_master_trx_no")
                        .HasColumnOrder(2);

                    b.Property<string>("n_add1_new")
                        .HasColumnType("text")
                        .HasColumnName("n_add1_new")
                        .HasColumnOrder(19);

                    b.Property<string>("n_add2_new")
                        .HasColumnType("text")
                        .HasColumnName("n_add2_new")
                        .HasColumnOrder(18);

                    b.Property<string>("n_address_type_code_detail_nominee")
                        .HasColumnType("text")
                        .HasColumnName("n_address_type_code_detail_nominee")
                        .HasColumnOrder(26);

                    b.Property<string>("n_address_type_code_nominee")
                        .HasColumnType("text")
                        .HasColumnName("n_address_type_code_nominee")
                        .HasColumnOrder(25);

                    b.Property<string>("n_cdsl_id_1_new")
                        .HasColumnType("text")
                        .HasColumnName("n_cdsl_id_1_new")
                        .HasColumnOrder(14);

                    b.Property<string>("n_city_new")
                        .HasColumnType("text")
                        .HasColumnName("n_city_new")
                        .HasColumnOrder(20);

                    b.Property<string>("n_cl_id_new")
                        .HasColumnType("text")
                        .HasColumnName("n_cl_id_new")
                        .HasColumnOrder(15);

                    b.Property<string>("n_country_new")
                        .HasColumnType("text")
                        .HasColumnName("n_country_new")
                        .HasColumnOrder(23);

                    b.Property<DateTime?>("n_date_of_att_majority_new")
                        .HasColumnType("date")
                        .HasColumnName("n_date_of_att_majority_new")
                        .HasColumnOrder(31);

                    b.Property<DateTime?>("n_dob_new")
                        .HasColumnType("date")
                        .HasColumnName("n_dob_new")
                        .HasColumnOrder(16);

                    b.Property<string>("n_email_new")
                        .HasColumnType("text")
                        .HasColumnName("n_email_new")
                        .HasColumnOrder(24);

                    b.Property<string>("n_f_m_w_name_new")
                        .HasColumnType("text")
                        .HasColumnName("n_f_m_w_name_new")
                        .HasColumnOrder(10);

                    b.Property<string>("n_gaurdian_address_new")
                        .HasColumnType("text")
                        .HasColumnName("n_gaurdian_address_new")
                        .HasColumnOrder(33);

                    b.Property<string>("n_gaurdian_name_new")
                        .HasColumnType("text")
                        .HasColumnName("n_gaurdian_name_new")
                        .HasColumnOrder(32);

                    b.Property<string>("n_gender_new")
                        .HasColumnType("text")
                        .HasColumnName("n_gender_new")
                        .HasColumnOrder(52);

                    b.Property<string>("n_m_f_new")
                        .HasColumnType("text")
                        .HasColumnName("n_m_f_new")
                        .HasColumnOrder(11);

                    b.Property<string>("n_name_new")
                        .HasColumnType("text")
                        .HasColumnName("n_name_new")
                        .HasColumnOrder(7);

                    b.Property<string>("n_nominee_is_a_minor_yn_new")
                        .HasColumnType("text")
                        .HasColumnName("n_nominee_is_a_minor_yn_new")
                        .HasColumnOrder(30);

                    b.Property<string>("n_nominee_opting_out_yn_new")
                        .HasColumnType("text")
                        .HasColumnName("n_nominee_opting_out_yn_new")
                        .HasColumnOrder(29);

                    b.Property<string>("n_nsdl_id_1_new")
                        .HasColumnType("text")
                        .HasColumnName("n_nsdl_id_1_new")
                        .HasColumnOrder(12);

                    b.Property<string>("n_nsdl_id_2_new")
                        .HasColumnType("text")
                        .HasColumnName("n_nsdl_id_2_new")
                        .HasColumnOrder(13);

                    b.Property<string>("n_occupation_det_new")
                        .HasColumnType("text")
                        .HasColumnName("n_occupation_det_new")
                        .HasColumnOrder(28);

                    b.Property<string>("n_occupation_det_new_code")
                        .HasColumnType("text")
                        .HasColumnName("n_occupation_det_new_code")
                        .HasColumnOrder(27);

                    b.Property<string>("n_pan_new")
                        .HasColumnType("text")
                        .HasColumnName("n_pan_new")
                        .HasColumnOrder(8);

                    b.Property<string>("n_phone_new")
                        .HasColumnType("text")
                        .HasColumnName("n_phone_new")
                        .HasColumnOrder(17);

                    b.Property<string>("n_pincode_new")
                        .HasColumnType("text")
                        .HasColumnName("n_pincode_new")
                        .HasColumnOrder(21);

                    b.Property<string>("n_relation_new")
                        .HasColumnType("text")
                        .HasColumnName("n_relation_new")
                        .HasColumnOrder(9);

                    b.Property<string>("n_state_new")
                        .HasColumnType("text")
                        .HasColumnName("n_state_new")
                        .HasColumnOrder(22);

                    b.Property<string>("n_update_type_nominee")
                        .HasColumnType("text")
                        .HasColumnName("n_update_type_nominee")
                        .HasColumnOrder(6);

                    b.Property<string>("rejecte_yn")
                        .HasColumnType("text")
                        .HasColumnName("rejecte_yn")
                        .HasColumnOrder(35);

                    b.Property<string>("rr_flag_name")
                        .HasColumnType("text")
                        .HasColumnName("rr_flag_name")
                        .HasColumnOrder(34);

                    b.Property<decimal?>("table_trf_no")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("table_trf_no")
                        .HasColumnOrder(1);

                    b.Property<string>("verify_by_user_name")
                        .HasColumnType("text")
                        .HasColumnName("verify_by_user_name")
                        .HasColumnOrder(37);

                    b.Property<string>("verify_remark")
                        .HasColumnType("text")
                        .HasColumnName("verify_remark")
                        .HasColumnOrder(39);

                    b.Property<string>("verify_status_msg")
                        .HasColumnType("text")
                        .HasColumnName("verify_status_msg")
                        .HasColumnOrder(38);

                    b.Property<DateTime?>("verify_updated_on")
                        .HasColumnType("datetime")
                        .HasColumnName("verify_updated_on")
                        .HasColumnOrder(40);

                    b.Property<string>("verify_yn")
                        .HasColumnType("text")
                        .HasColumnName("verify_yn")
                        .HasColumnOrder(36);

                    b.HasKey("id");

                    b.HasIndex("holder_detail_id");

                    b.ToTable("NomineeDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.PowerAttorney", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint auto_increment")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("folio_id")
                        .HasColumnType("text")
                        .HasColumnName("folio_id")
                        .HasColumnOrder(3);

                    b.Property<string>("foliono")
                        .HasColumnType("text")
                        .HasColumnName("foliono")
                        .HasColumnOrder(2);

                    b.Property<long?>("foliono_auto_id")
                        .HasColumnType("bigint")
                        .HasColumnName("foliono_auto_id")
                        .HasColumnOrder(0);

                    b.Property<decimal?>("foliono_number")
                        .HasColumnType("decimal(18,0)")
                        .HasColumnName("foliono_number")
                        .HasColumnOrder(1);

                    b.Property<long?>("holder_detail_id")
                        .HasColumnType("bigint")
                        .HasColumnName("holder_detail_id")
                        .HasColumnOrder(56);

                    b.Property<string>("old_folio_no_id")
                        .HasColumnType("text")
                        .HasColumnName("old_folio_no_id")
                        .HasColumnOrder(4);

                    b.Property<string>("power_attorney_Add1")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Add1")
                        .HasColumnOrder(15);

                    b.Property<string>("power_attorney_Add2")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Add2")
                        .HasColumnOrder(16);

                    b.Property<string>("power_attorney_City")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_City")
                        .HasColumnOrder(17);

                    b.Property<string>("power_attorney_Country")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Country")
                        .HasColumnOrder(20);

                    b.Property<DateTime?>("power_attorney_Date")
                        .HasColumnType("date")
                        .HasColumnName("power_attorney_Date")
                        .HasColumnOrder(7);

                    b.Property<DateTime?>("power_attorney_Dob")
                        .HasColumnType("date")
                        .HasColumnName("power_attorney_Dob")
                        .HasColumnOrder(13);

                    b.Property<string>("power_attorney_Email")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Email")
                        .HasColumnOrder(21);

                    b.Property<string>("power_attorney_F_M_W_Name")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_F_M_W_Name")
                        .HasColumnOrder(12);

                    b.Property<string>("power_attorney_M_F")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_M_F")
                        .HasColumnOrder(14);

                    b.Property<string>("power_attorney_Name")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Name")
                        .HasColumnOrder(8);

                    b.Property<string>("power_attorney_PanNo")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_PanNo")
                        .HasColumnOrder(10);

                    b.Property<string>("power_attorney_Phone")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Phone")
                        .HasColumnOrder(22);

                    b.Property<string>("power_attorney_Pincode")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Pincode")
                        .HasColumnOrder(18);

                    b.Property<string>("power_attorney_Relation")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Relation")
                        .HasColumnOrder(11);

                    b.Property<string>("power_attorney_State")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_State")
                        .HasColumnOrder(19);

                    b.Property<string>("power_attorney_TrfNo")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_TrfNo")
                        .HasColumnOrder(6);

                    b.Property<string>("power_attorney_Type")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_Type")
                        .HasColumnOrder(9);

                    b.Property<string>("power_attorney_exist_YN")
                        .HasColumnType("text")
                        .HasColumnName("power_attorney_exist_YN")
                        .HasColumnOrder(5);

                    b.HasKey("id");

                    b.HasIndex("holder_detail_id");

                    b.ToTable("PowerAttorney");
                });

            modelBuilder.Entity("DB.Login.Tables.ProcessRequestDetail", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<long?>("general_requested_detail_id")
                        .HasColumnType("bigint")
                        .HasColumnName("general_requested_detail_id")
                        .HasColumnOrder(4);

                    b.Property<string>("required_info")
                        .HasColumnType("text")
                        .HasColumnName("required_info")
                        .HasColumnOrder(2);

                    b.Property<string>("required_info_data")
                        .HasColumnType("text")
                        .HasColumnName("required_info_data")
                        .HasColumnOrder(3);

                    b.HasKey("id");

                    b.HasIndex("general_requested_detail_id");

                    b.ToTable("ProcessRequestDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.ServiceMaster", b =>
                {
                    b.Property<long>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasColumnOrder(1);

                    b.Property<string>("service_name")
                        .HasColumnType("text")
                        .HasColumnName("service_name")
                        .HasColumnOrder(2);

                    b.HasKey("id");

                    b.ToTable("ServiceMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.CategoryMaster", b =>
                {
                    b.HasOne("DB.Login.Tables.ServiceMaster", "ServiceMaster")
                        .WithMany("CategoryMaster")
                        .HasForeignKey("service_id");

                    b.Navigation("ServiceMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.CheckListMaster", b =>
                {
                    b.HasOne("DB.Login.Tables.CategoryMaster", "CategoryMaster")
                        .WithMany("CheckListMaster")
                        .HasForeignKey("category_id");

                    b.Navigation("CategoryMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.GeneralRequestedDetail", b =>
                {
                    b.HasOne("DB.Login.Tables.CategoryMaster", "CategoryMaster")
                        .WithMany()
                        .HasForeignKey("category_id");

                    b.HasOne("DB.Login.Tables.ServiceMaster", "ServiceMaster")
                        .WithMany("GeneralRequestedDetails")
                        .HasForeignKey("service_id");

                    b.Navigation("CategoryMaster");

                    b.Navigation("ServiceMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.KYCDetail", b =>
                {
                    b.HasOne("DB.Login.Tables.HolderDetail", "HolderDetail")
                        .WithMany("KYCDetail")
                        .HasForeignKey("holder_detail_id");

                    b.Navigation("HolderDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.NomineeDetail", b =>
                {
                    b.HasOne("DB.Login.Tables.HolderDetail", "HolderDetail")
                        .WithMany("NomineeDetail")
                        .HasForeignKey("holder_detail_id");

                    b.Navigation("HolderDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.PowerAttorney", b =>
                {
                    b.HasOne("DB.Login.Tables.HolderDetail", "HolderDetail")
                        .WithMany()
                        .HasForeignKey("holder_detail_id");

                    b.Navigation("HolderDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.ProcessRequestDetail", b =>
                {
                    b.HasOne("DB.Login.Tables.GeneralRequestedDetail", "GeneralRequestedDetail")
                        .WithMany("ProcessRequestDetail")
                        .HasForeignKey("general_requested_detail_id");

                    b.Navigation("GeneralRequestedDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.CategoryMaster", b =>
                {
                    b.Navigation("CheckListMaster");
                });

            modelBuilder.Entity("DB.Login.Tables.GeneralRequestedDetail", b =>
                {
                    b.Navigation("ProcessRequestDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.HolderDetail", b =>
                {
                    b.Navigation("KYCDetail");

                    b.Navigation("NomineeDetail");
                });

            modelBuilder.Entity("DB.Login.Tables.ServiceMaster", b =>
                {
                    b.Navigation("CategoryMaster");

                    b.Navigation("GeneralRequestedDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
